### ISSUE TITLE
Bug: imports repeat and need cancelling

### ISSUE THREAD

**Issue by joshmoore** [ome/omero-dropbox#14]
see: https://forum.image.sc/t/omero-pyramid-generation-time/33463/21

> I copied a folder, which has three nested folders, to my “watchDir”. As I expected, the importing
of the images started automatically. The first folder has text files only. This folder was not imported. It is what I expected. The second folder has both text files and images. Only images were imported. It is what I expected too. The third folder has images only. Images were imported. But the importing did not stop. It repeated. So I stopped the DropBox in the middle of the 3rd repetition.

**Comment by joshmoore** [comment]
Looking at the logs, there's a fairly straight-forward error:

```
2020-03-27 18:27:06,013 WARNI [                                  stderr] (Thread-785) Exception in thread Thread-785:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/opt/omero/server/venv3/lib/python3.6/site-packages/omero/util/concurrency.py", line 109, in run
    self.function(*self.args, **self.kwargs)
  File "/opt/omero/server/venv3/lib/python3.6/site-packages/fsDropBoxMonitorClient.py", line 525, in importFileWrapper
    self.importFile(fileId, exName)
  File "/opt/omero/server/venv3/lib/python3.6/site-packages/omero/util/decorators.py", line 29, in handler
    return func(*args, **kwargs)
  File "/opt/omero/server/venv3/lib/python3.6/site-packages/fsDropBoxMonitorClient.py", line 684, in importFile
    remove_path(t)
UnboundLocalError: local variable 't' referenced before assignment
```

Unclear if this is the cause of the repeats.
